config:
  dryRun: true
  logLevel: debug
  logFormat: console
  imageSwapPolicy: exists
  imageCopyPolicy: delayed
  imageCopyDeadline: 30s

source:
  filters:
    - jmespath: "obj.metadata.namespace != 'kube-system'"
    - jmespath: "obj.metadata.namespace == 'image-swapper-test'"

target:
  type: aws
  aws:
    accountId: "<AWS_ACCOUNT_ID>"
    region: "us-east-1"

imageSwapper:
  enabled: false

secretReader:
  enabled: true

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::<AWS_ACCOUNT_ID>:role/<ROLE_NAME>"
